export const ActionType = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",

  FETCH_COUNTRIES_START: "FETCH_COUNTRIES_START",
  FETCH_COUNTRIES_COMPLETE: "FETCH_COUNTRIES_COMPLETE",
};
